package JMS.Message;

public enum Events {
    SERVER_START,
    ACCOUNT_CREATED,
    ACCOUNT_MODIFIED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_LOGGED_IN,
    USER_MODIFIED_PRECENSE,
    GROUP_CREATED,
    GROUP_MODIFIED,
    GROUP_REMOVED,
    TASK_CREATED,
    TASK_MODIFIED,
    TASK_REMOVED,
    TASK_COMPLETED,
    TASK_EXCHANGED,
    MAIL_SEND
}